# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Calculate Code Coverage
      uses: maxep/spm-lcov-action@0.3.1
      with:
        output-file: coverage.json
        file-format: text
